[package]
name = "ccver"
version = "0.1.0"
edition = "2021"
authors = ["Ryan Guild <rdg27@pitt.edu>"]



[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
indoc = "2"

[dependencies]
chrono = {version = "0.4.39", default-features = true}
pest_derive = {version = "2.7.15", default-features = false}
pest = {version = "2.7.15", default-features = false}
# serde = { version = "1.0.217", features = ["derive"], default-features = false}
clap = { version = "4.5.27", features = ["derive"] }
pest_consume = "1.1.3"
# figment = { version = "0.10.19", features = ["json"] }
eyre = "0.6.12"
petgraph = {version = "0.7.1", features = ["graphmap"], default-features = false}
