name: CI/CD

on:
  workflow_dispatch: {}
  push: {}


permissions:
  contents: write
  id-token: write
  attestations: write
  checks: write
  packages: write
  security-events: write


jobs:
  check:
    name: Check
    secrets: inherit
    uses: "./.github/workflows/tag.yml"
  build:
    name: Build
    secrets: inherit
    uses: "./.github/workflows/build.yml"
  sbom:
    name: SBOM
    needs: build
    uses: "./.github/workflows/sbom.yml"
  docker:
    name: Docker
    needs: [build, sbom]
    secrets: inherit
    uses: "./.github/workflows/docker.yml"
  profile:
    name: Profile
    secrets: inherit
    uses: "./.github/workflows/profile.yml"
  test:
    name: Test
    uses: "./.github/workflows/test.yml"
  test-action:
    needs: docker
    name: Test Action
    uses: "./.github/workflows/test-action.yml"
  release:
    name: Release
    if: github.ref_name == 'main' || github.ref_name == 'master'
    needs: [check, build, sbom, test, test-action, docker, profile]
    uses: "./.github/workflows/release.yml"
    secrets: inherit
    with:
      tag: ${{ github.ref_name }}
