name: CI/CD

on:
  workflow_dispatch: {}
  push: {}


permissions:
  contents: write
  id-token: write
  attestations: write
  checks: write



jobs:
  build:
    name: Build
    secrets: inherit
    uses: "./.github/workflows/build.yaml"
  test:
    name: Test
    uses: "./.github/workflows/test.yaml"
  release:
    name: Release
    if: github.ref_name == 'main' || github.ref_name == 'master'
    needs: [build, test]
    uses: "./.github/workflows/release.yaml"
    secrets: inherit
    with:
      tag: ${{ github.ref_name }}
