name: CI/CD

on:
  workflow_dispatch: {}
  push: {}


permissions:
  contents: write
  id-token: write
  attestations: write
  checks: write



jobs:
  prebuild:
    name: Prebuild
    uses: "./.github/workflows/prebuild.yaml"
  build:
    name: Build
    needs: prebuild
    secrets: inherit
    uses: "./.github/workflows/build.yaml"
  selftag:
    name: Version
    needs: build
    uses: "./.github/workflows/selftag.yaml"
  test:
    name: Test
    needs: build
    uses: "./.github/workflows/test.yaml"
  release:
    name: Release
    needs: [build, selftag, test]
    uses: "./.github/workflows/release.yaml"
    if: ${{!contains(needs.selftag.outputs.version, '-')}}
    with:
      tag: ${{ needs.selftag.outputs.version }}

