name: Prebuild

on:
  workflow_call: {}

permissions:
  contents: write


jobs:
  fmt:
    name: 🧹 Format Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Get Rust Cache
        uses: ./.github/actions/rust_depcache
        with:
          runner: ubuntu-latest
          arch: x86_64-unknown-linux-gnu
          rust: nightly
      - name: Format Code
        run: cargo fmt --all
      - name: Check for changes
        id: git-diff
        run: git diff --exit-code
        continue-on-error: true
      - name: Commit changes
        if: steps.git-diff.outcome == 'failure'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "chore: Format code"
          git pull --ff-only
          git push
      - name: Error if changes
        if: steps.git-diff.outcome == 'failure'
        run: exit 1


  fix:
    name: 🔬 Fix Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Get Rust Cache
        uses: ./.github/actions/rust_depcache
        with:
          runner: ubuntu-latest
          arch: x86_64-unknown-linux-gnu
          rust: nightly
      - name: Fix Code
        run: cargo fix
      - name: Check for changes
        id: git-diff
        run: git diff --exit-code
        continue-on-error: true
      - name: Commit changes
        if: steps.git-diff.outcome == 'failure'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "chore: Fix code"
          git pull --ff-only
          git push


  cargo_toml_version:
    needs: [fmt, fix]
    name: 📦 Update Cargo.toml Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          fetch-tags: true
      - name: Get Rust Cache
        uses: ./.github/actions/rust_depcache
        with:
          runner: ubuntu-latest
          arch: x86_64-unknown-linux-gnu
          rust: nightly
      - name: Get Version
        id: get_version
        run: echo "version=$(cargo run -- --format CC.CC.CC --no-pre)" >> "$GITHUB_OUTPUT"
      - name: Bump Version
        uses: sandstromviktor/toml-editor@2.0.0
        with:
          file: "Cargo.toml"
          key: "package.version"
          value: ${{ steps.get_version.outputs.version }}
      - name: Check for changes
        id: git-diff
        run: git diff --exit-code
        continue-on-error: true
      - name: Commit changes
        if: steps.git-diff.outcome == 'failure'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "chore: Update Cargo.toml version"
          git pull --ff-only
          git push
