name: Prebuild

on: 
  workflow_call: {}


jobs:
  fmt:
    name: 🧹 Format Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Rust Cache
        uses: ./.github/actions/rust_depcache
        with:
          runner: ubuntu-latest
          arch: x86_64-unknown-linux-gnu
          rust: nightly
      - name: Format Code
        run: cargo fmt --all -- --check
      - name: Check for changes
        id: git-diff
        run: git diff --exit-code
      - name: Commit changes
        if: steps.git-diff.outputs.exit_code != 0
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "chore: Format code"
          git push
      - name: Error if changes
        if: steps.git-diff.outputs.exit_code != 0
        run: exit 1


  fix:
    name: 🔬 Fix Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Rust Cache
        uses: ./.github/actions/rust_depcache
        with:
          runner: ubuntu-latest
          arch: x86_64-unknown-linux-gnu
          rust: nightly
      - name: Fix Code
        run: cargo fix --allow-dirty --allow-staged
      - name: Check for changes
        id: git-diff
        run: git diff --exit-code
      - name: Commit changes
        if: steps.git-diff.outputs.exit_code != 0
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "chore: Fix code"
          git push
      - name: Error if changes
        if: steps.git-diff.outputs.exit_code != 0
        run: exit 1
