name: Update Version and Tag

on:
  workflow_call: {}

permissions:
  contents: write

jobs:
  update-version:
    name: 📝 Update Version in Cargo.toml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Rust Cache
        uses: ./.github/actions/rust_depcache
        with:
          runner: ubuntu-latest
          arch: x86_64-unknown-linux-gnu
          rust: nightly

      - name: Run version updater
        id: update-cargo-toml-version
        run: cargo run --bin update-cargo-toml-version --release

      - name: Check for changes
        id: check-for-changes
        run: |
          if git diff --quiet Cargo.toml; then
            echo "No changes to Cargo.toml"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes to Cargo.toml"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit change
        if: steps.check-for-changes.outputs.changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Cargo.toml
          git commit -m "chore: update version in Cargo.toml"
          git push

      - name: Fail workflow if changes were made
        if: steps.check-for-changes.outputs.changes == 'true'
        run: |
          echo "::error::Version was updated in Cargo.toml. Please re-run the workflow with the updated version."
          exit 1
