name: Update Version and Tag

on:
  workflow_call: {}

permissions:
  contents: write

jobs:
  update-version:
    name: 📝 Update Version in Cargo.toml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Rust Cache
        uses: ./.github/actions/rust_depcache
        with:
          runner: ubuntu-latest
          arch: x86_64-unknown-linux-gnu
          rust: nightly

      - name: Run version updater
        id: check-cargo-toml-version
        run: cargo run --bin check-cargo-toml-version --release
        continue-on-error: true

      - name: Commit changes
        if: steps.check-cargo-toml-version.conclusion == 'success'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Cargo.toml
          git commit -m "chore: update version in Cargo.toml"
          git push

      - name: Fail workflow if changes were made
        if: steps.changes.outputs.changed == 'true'
        run: |
          echo "::error::Version was updated in Cargo.toml. Please re-run the workflow with the updated version."
          exit 1
