name: Test Report

on: 
  push:
  check_suite: 

permissions: 
  checks: write

jobs:
  test:
    name: Test Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
      - name: Install Junitify
        run: cargo install junitify
      - name: Run Tests
        run: cargo test -- --format=json -Z unstable-options --report-time | junitify --out tests/
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests            # Name of the check run which will be created
          path: tests/*.xml    # Path to test results
          reporter: java-junit