name: Test CCVer Action on Docker Image

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types: [completed]
    branches: [main, master]

jobs:
  test-action:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
    - name: Test CCVer Action - Get Version
      id: version
      uses: ryanguild/ccver@master
      with:
        ci: 'false'

    - name: Test CCVer Action - Generate Changelog
      id: changelog
      uses: ryanguild/ccver@master
      with:
        command: 'changelog'
        ci: 'false'

    - name: Test CCVer Action - Custom Format
      id: custom
      uses: ryanguild/ccver@master
      with:
        format: 'v{major}.{minor}.{patch}'
        ci: 'false'

    - name: Display Results
      run: |
        echo "Default version: ${{ steps.version.outputs.version }}"
        echo "Custom format version: ${{ steps.custom.outputs.version }}"
        echo "Changelog:"
        echo "${{ steps.changelog.outputs.changelog }}"

  test-docker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
    - name: Login to GHCR.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Pull Docker Image
      run: docker pull ghcr.io/ryanguild/ccver:${{ github.ref_name }}

    - name: Test Docker Image - HELP
      run: docker run --rm -v "${GITHUB_WORKSPACE}:/github/workspace" ghcr.io/ryanguild/ccver:${{ github.ref_name }} --help

    - name: Test Docker Image - CHANGELOG
      run: docker run --rm -v "${GITHUB_WORKSPACE}:/github/workspace" ghcr.io/ryanguild/ccver:${{ github.ref_name }} changelog

    - name: Test Docker Image - Version
      run: docker run --rm -v "${GITHUB_WORKSPACE}:/github/workspace" ghcr.io/ryanguild/ccver:${{ github.ref_name }}
