name: Test CCVer Action

on: [push, pull_request]

jobs:
  test-basic:
    runs-on: ubuntu-latest
    name: Test Basic Version Output
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run CCVer Action
        id: ccver
        uses: ./
        with:
          path: '.'
          ci: 'false'

      - name: Print Version
        run: |
          echo "Version: ${{ steps.ccver.outputs.version }}"

  test-changelog:
    runs-on: ubuntu-latest
    name: Test Changelog Generation
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Changelog
        id: changelog
        uses: ./
        with:
          path: '.'
          command: 'changelog'
          ci: 'false'

      - name: Print Changelog
        run: |
          echo "Changelog:"
          echo "${{ steps.changelog.outputs.changelog }}"
