name: Create Test Report

on: 
  workflow_call: {}

permissions: 
  checks: write

jobs:
  test:
    name: ❓ Create Test Report
    runs-on: ${{ matrix.target.runner }}
    strategy:
      matrix:
        rust: [nightly]
        target:
          - runner: ubuntu-latest
            arch: x86_64-unknown-linux-gnu
          - runner: windows-latest
            arch: x86_64-pc-windows-msvc
          - runner: macos-latest
            arch: aarch64-apple-darwin
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          fetch-tags: true
      - name: Get Rust Cache
        uses: ./.github/actions/rust_depcache
        with:
          runner: ${{ matrix.target.runner }}
          arch: ${{ matrix.target.arch }}
          rust: ${{ matrix.rust }}
      - name: Install Junitify
        run: cargo install junitify
      - name: Run Tests
        run: cargo test -- --format=json -Z unstable-options --report-time | junitify --out tests/
      - name: Test Report
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: ${{matrix.target.runner}} Tests          # Name of the check run which will be created
          path: tests/*.xml    # Path to test results
          reporter: java-junit
          fail-on-error: false
          fail-on-empty: true